# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(279, 594)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 30, 281, 581))
        self.stackedWidget.setObjectName("stackedWidget")
        self.get_started = QtWidgets.QWidget()
        self.get_started.setObjectName("get_started")
        self.dog = QtWidgets.QLabel(parent=self.get_started)
        self.dog.setEnabled(True)
        self.dog.setGeometry(QtCore.QRect(10, 20, 251, 311))
        self.dog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dog.setText("")
        self.dog.setPixmap(QtGui.QPixmap("dog.png"))
        self.dog.setScaledContents(True)
        self.dog.setObjectName("dog")
        self.background_page_1 = QtWidgets.QLineEdit(parent=self.get_started)
        self.background_page_1.setEnabled(False)
        self.background_page_1.setGeometry(QtCore.QRect(10, 30, 261, 541))
        self.background_page_1.setStyleSheet("background-color: #aaff7f;\n"
"border-radius: 20px;\n"
"\n"
"")
        self.background_page_1.setObjectName("background_page_1")
        self.get_started_bt = QtWidgets.QPushButton(parent=self.get_started)
        self.get_started_bt.setGeometry(QtCore.QRect(70, 500, 141, 31))
        self.get_started_bt.setStyleSheet("backgroud-color:#ffffff;")
        self.get_started_bt.setObjectName("get_started_bt")
        self.label_2 = QtWidgets.QLabel(parent=self.get_started)
        self.label_2.setGeometry(QtCore.QRect(50, 310, 221, 41))
        self.label_2.setStyleSheet("font: 700 16pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.background_page_1.raise_()
        self.dog.raise_()
        self.get_started_bt.raise_()
        self.label_2.raise_()
        self.stackedWidget.addWidget(self.get_started)
        self.whity_page = QtWidgets.QWidget()
        self.whity_page.setObjectName("whity_page")
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=self.whity_page)
        self.textBrowser_4.setGeometry(QtCore.QRect(20, 350, 241, 131))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_14 = QtWidgets.QLabel(parent=self.whity_page)
        self.label_14.setGeometry(QtCore.QRect(18, 315, 141, 31))
        self.label_14.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"font: 700 16pt \"Segoe UI\";")
        self.label_14.setObjectName("label_14")
        self.background_page_6 = QtWidgets.QLineEdit(parent=self.whity_page)
        self.background_page_6.setEnabled(False)
        self.background_page_6.setGeometry(QtCore.QRect(10, 30, 261, 541))
        self.background_page_6.setStyleSheet("background-color: #aaff7f;\n"
"border-radius: 20px;\n"
"\n"
"")
        self.background_page_6.setObjectName("background_page_6")
        self.label_13 = QtWidgets.QLabel(parent=self.whity_page)
        self.label_13.setGeometry(QtCore.QRect(20, 80, 241, 231))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("dog3.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.homepage_bt = QtWidgets.QPushButton(parent=self.whity_page)
        self.homepage_bt.setGeometry(QtCore.QRect(20, 530, 241, 24))
        self.homepage_bt.setObjectName("homepage_bt")
        self.background_page_6.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.textBrowser_4.raise_()
        self.homepage_bt.raise_()
        self.stackedWidget.addWidget(self.whity_page)
        self.homepage = QtWidgets.QWidget()
        self.homepage.setObjectName("homepage")
        self.background_page_2 = QtWidgets.QLineEdit(parent=self.homepage)
        self.background_page_2.setEnabled(False)
        self.background_page_2.setGeometry(QtCore.QRect(10, 30, 261, 541))
        self.background_page_2.setStyleSheet("background-color: #aaff7f;\n"
"border-radius: 20px;\n"
"\n"
"")
        self.background_page_2.setObjectName("background_page_2")
        self.label_3 = QtWidgets.QLabel(parent=self.homepage)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 131, 91))
        self.label_3.setStyleSheet("\n"
"font: 14pt \"Segoe UI\";")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.push_button_1 = QtWidgets.QPushButton(parent=self.homepage)
        self.push_button_1.setGeometry(QtCore.QRect(20, 300, 101, 101))
        self.push_button_1.setText("")
        self.push_button_1.setObjectName("push_button_1")
        self.melina_1 = QtWidgets.QLabel(parent=self.homepage)
        self.melina_1.setEnabled(True)
        self.melina_1.setGeometry(QtCore.QRect(30, 370, 49, 16))
        self.melina_1.setObjectName("melina_1")
        self.cat_1 = QtWidgets.QLabel(parent=self.homepage)
        self.cat_1.setEnabled(True)
        self.cat_1.setGeometry(QtCore.QRect(20, 280, 101, 81))
        self.cat_1.setAutoFillBackground(False)
        self.cat_1.setText("")
        self.cat_1.setPixmap(QtGui.QPixmap("cat.png"))
        self.cat_1.setScaledContents(True)
        self.cat_1.setObjectName("cat_1")
        self.push_button_3 = QtWidgets.QPushButton(parent=self.homepage)
        self.push_button_3.setGeometry(QtCore.QRect(20, 440, 101, 101))
        self.push_button_3.setText("")
        self.push_button_3.setObjectName("push_button_3")
        self.melina_2 = QtWidgets.QLabel(parent=self.homepage)
        self.melina_2.setEnabled(True)
        self.melina_2.setGeometry(QtCore.QRect(30, 510, 49, 16))
        self.melina_2.setObjectName("melina_2")
        self.label_8 = QtWidgets.QLabel(parent=self.homepage)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(30, 420, 101, 81))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("dog2.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.cat_3 = QtWidgets.QLabel(parent=self.homepage)
        self.cat_3.setEnabled(True)
        self.cat_3.setGeometry(QtCore.QRect(130, 280, 111, 91))
        self.cat_3.setAutoFillBackground(False)
        self.cat_3.setText("")
        self.cat_3.setPixmap(QtGui.QPixmap("cat2.png"))
        self.cat_3.setScaledContents(True)
        self.cat_3.setObjectName("cat_3")
        self.melina_3 = QtWidgets.QLabel(parent=self.homepage)
        self.melina_3.setEnabled(True)
        self.melina_3.setGeometry(QtCore.QRect(150, 370, 49, 16))
        self.melina_3.setObjectName("melina_3")
        self.push_button_2 = QtWidgets.QPushButton(parent=self.homepage)
        self.push_button_2.setGeometry(QtCore.QRect(140, 300, 101, 101))
        self.push_button_2.setText("")
        self.push_button_2.setObjectName("push_button_2")
        self.cat_4 = QtWidgets.QLabel(parent=self.homepage)
        self.cat_4.setEnabled(True)
        self.cat_4.setGeometry(QtCore.QRect(160, 420, 61, 81))
        self.cat_4.setAutoFillBackground(False)
        self.cat_4.setText("")
        self.cat_4.setPixmap(QtGui.QPixmap("dog3.png"))
        self.cat_4.setScaledContents(True)
        self.cat_4.setObjectName("cat_4")
        self.melina_4 = QtWidgets.QLabel(parent=self.homepage)
        self.melina_4.setEnabled(True)
        self.melina_4.setGeometry(QtCore.QRect(150, 510, 49, 16))
        self.melina_4.setObjectName("melina_4")
        self.push_button_4 = QtWidgets.QPushButton(parent=self.homepage)
        self.push_button_4.setGeometry(QtCore.QRect(140, 440, 101, 101))
        self.push_button_4.setText("")
        self.push_button_4.setObjectName("push_button_4")
        self.label_7 = QtWidgets.QLabel(parent=self.homepage)
        self.label_7.setGeometry(QtCore.QRect(80, 40, 131, 41))
        self.label_7.setStyleSheet("font: 18pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.background_page_2.raise_()
        self.label_3.raise_()
        self.push_button_1.raise_()
        self.melina_1.raise_()
        self.cat_1.raise_()
        self.push_button_3.raise_()
        self.melina_2.raise_()
        self.label_8.raise_()
        self.push_button_2.raise_()
        self.cat_3.raise_()
        self.melina_3.raise_()
        self.push_button_4.raise_()
        self.melina_4.raise_()
        self.cat_4.raise_()
        self.label_7.raise_()
        self.stackedWidget.addWidget(self.homepage)
        self.balmoso_page = QtWidgets.QWidget()
        self.balmoso_page.setObjectName("balmoso_page")
        self.label_12 = QtWidgets.QLabel(parent=self.balmoso_page)
        self.label_12.setGeometry(QtCore.QRect(20, 60, 241, 231))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("dog2.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(parent=self.balmoso_page)
        self.label_10.setGeometry(QtCore.QRect(20, 310, 141, 31))
        self.label_10.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"font: 700 16pt \"Segoe UI\";")
        self.label_10.setObjectName("label_10")
        self.background_page_5 = QtWidgets.QLineEdit(parent=self.balmoso_page)
        self.background_page_5.setEnabled(False)
        self.background_page_5.setGeometry(QtCore.QRect(10, 30, 261, 541))
        self.background_page_5.setStyleSheet("background-color: #aaff7f;\n"
"border-radius: 20px;\n"
"\n"
"")
        self.background_page_5.setObjectName("background_page_5")
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=self.balmoso_page)
        self.textBrowser_3.setEnabled(False)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 360, 241, 131))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.homepage_bt_2 = QtWidgets.QPushButton(parent=self.balmoso_page)
        self.homepage_bt_2.setGeometry(QtCore.QRect(20, 540, 241, 24))
        self.homepage_bt_2.setObjectName("homepage_bt_2")
        self.background_page_5.raise_()
        self.textBrowser_3.raise_()
        self.label_12.raise_()
        self.label_10.raise_()
        self.homepage_bt_2.raise_()
        self.stackedWidget.addWidget(self.balmoso_page)
        self.rosas_page = QtWidgets.QWidget()
        self.rosas_page.setObjectName("rosas_page")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.rosas_page)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 360, 241, 131))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.background_page_4 = QtWidgets.QLineEdit(parent=self.rosas_page)
        self.background_page_4.setEnabled(False)
        self.background_page_4.setGeometry(QtCore.QRect(10, 30, 261, 541))
        self.background_page_4.setStyleSheet("background-color: #aaff7f;\n"
"border-radius: 20px;\n"
"\n"
"")
        self.background_page_4.setObjectName("background_page_4")
        self.label_6 = QtWidgets.QLabel(parent=self.rosas_page)
        self.label_6.setGeometry(QtCore.QRect(20, 310, 141, 31))
        self.label_6.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"font: 700 16pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(parent=self.rosas_page)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 241, 211))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("cat2.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.homepage_bt_3 = QtWidgets.QPushButton(parent=self.rosas_page)
        self.homepage_bt_3.setGeometry(QtCore.QRect(20, 530, 241, 24))
        self.homepage_bt_3.setObjectName("homepage_bt_3")
        self.background_page_4.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.textBrowser_2.raise_()
        self.homepage_bt_3.raise_()
        self.stackedWidget.addWidget(self.rosas_page)
        self.melina_page = QtWidgets.QWidget()
        self.melina_page.setObjectName("melina_page")
        self.background_page_3 = QtWidgets.QLineEdit(parent=self.melina_page)
        self.background_page_3.setEnabled(False)
        self.background_page_3.setGeometry(QtCore.QRect(10, 30, 261, 541))
        self.background_page_3.setStyleSheet("background-color: #aaff7f;\n"
"border-radius: 20px;\n"
"\n"
"")
        self.background_page_3.setObjectName("background_page_3")
        self.label = QtWidgets.QLabel(parent=self.melina_page)
        self.label.setGeometry(QtCore.QRect(20, 60, 241, 231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("cat.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=self.melina_page)
        self.label_4.setGeometry(QtCore.QRect(18, 315, 141, 31))
        self.label_4.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"font: 700 16pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.melina_page)
        self.textBrowser.setGeometry(QtCore.QRect(20, 350, 241, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.homepage_bt_4 = QtWidgets.QPushButton(parent=self.melina_page)
        self.homepage_bt_4.setGeometry(QtCore.QRect(20, 530, 241, 24))
        self.homepage_bt_4.setObjectName("homepage_bt_4")
        self.stackedWidget.addWidget(self.melina_page)
        self.samsung = QtWidgets.QLabel(parent=Form)
        self.samsung.setGeometry(QtCore.QRect(0, 0, 291, 601))
        self.samsung.setText("")
        self.samsung.setPixmap(QtGui.QPixmap("images.jpg"))
        self.samsung.setScaledContents(True)
        self.samsung.setObjectName("samsung")
        self.date_label = QtWidgets.QLabel(parent=Form)
        self.date_label.setGeometry(QtCore.QRect(140, 0, 131, 16))
        self.date_label.setStyleSheet("QLabel {\n"
"        color: white;\n"
"    }")
        self.date_label.setText("")
        self.date_label.setObjectName("date_label")
        self.emergency_label = QtWidgets.QLabel(parent=Form)
        self.emergency_label.setGeometry(QtCore.QRect(0, 0, 91, 16))
        self.emergency_label.setStyleSheet("QLabel {\n"
"        color: white;\n"
"    }")
        self.emergency_label.setText("")
        self.emergency_label.setObjectName("emergency_label")
        self.samsung.raise_()
        self.stackedWidget.raise_()
        self.date_label.raise_()
        self.emergency_label.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.get_started_bt.setText(_translate("Form", "Get Started"))
        self.label_2.setText(_translate("Form", "Find Love With Us"))
        self.textBrowser_4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Whity is a good cat</p></body></html>"))
        self.label_14.setText(_translate("Form", "Whity"))
        self.homepage_bt.setText(_translate("Form", "Homepage"))
        self.label_3.setText(_translate("Form", "For your Love"))
        self.melina_1.setText(_translate("Form", "Melina"))
        self.melina_2.setText(_translate("Form", "Balmoso"))
        self.melina_3.setText(_translate("Form", "Rosas"))
        self.melina_4.setText(_translate("Form", "Whity"))
        self.label_7.setText(_translate("Form", " Homepage"))
        self.label_10.setText(_translate("Form", "Balmoso"))
        self.textBrowser_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Balmoso History was little bit dramatic since his owner, abbandon him.Despite the loss of his beloved owner  he remain optimistic in life.early abbadonment owner becouse of death this give opportunity to this dog to remain in life.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.homepage_bt_2.setText(_translate("Form", "Homepage"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Rosas Is A good Cat</p></body></html>"))
        self.label_6.setText(_translate("Form", "Rosas"))
        self.homepage_bt_3.setText(_translate("Form", "Homepage"))
        self.label_4.setText(_translate("Form", "Melina"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Melina was a good cat she was  3 months years old</p></body></html>"))
        self.homepage_bt_4.setText(_translate("Form", "Homepage"))
